### ISSUE TITLE
Pinephone comptible

### ISSUE THREAD

**Issue by Frick-David** [pia-foss/desktop#18]
can this be made pinephone compatible? It installs find under postmarketos. However, the client does not show on the screen when the program is launched.

**Comment by JonathonH-PIA** [comment]
Hi @Frick-David , it looks like the PinePhone is an arm64 device.  We now have arm64 and armhf builds for our latest beta and I'd like to know how it works for you if you can give it a try!  https://github.com/pia-foss/desktop/releases/tag/2.6.2-beta.1

I've tried this on some other Pine64 boards (mainly RockPro64) but I don't have a PinePhone, and I haven't tried PostmarketOS.  I've mainly been using ARMbian.

Give this a try and let us know how it works for you!  I'm also interested in build feedback if you'd like to try building it.  We use Debian Stretch environments for cross builds, if you have `schroot` and `debootstrap` you can set these up with `scripts/chroot/setup.sh`.  You can also install the cross build dependencies in your host OS, but we haven't tested this on Arch.

I'll close this issue since this is now in beta, but please send us feedback or open issues if you find bugs!
