### ISSUE TITLE
Releases for aarch64

### ISSUE THREAD

**Issue by kevinlekiller** [pia-foss/desktop#6]
The installer at **https://www.privateinternetaccess.com/installer/x/download_installer_linux**
runs and completes fine on [Manjaro Linux Arm 64 bit](https://www.manjaro.org/download/#raspberry-pi-4-kde-plasma), but the binaries are compiled for x86_64 so they fail to run on aarch64, would it be possible to add aarch64 support to the installer?

**Comment by JonathonH-PIA** [comment]
We'd like to support more architectures, but we don't have it on our roadmap right now.  All of our dependencies theoretically should work on aarch64 if you would like to try compiling yourself!

The sticking point will be Qt - we build with the standalone Qt distribution from qt.io, but they don't ship builds for aarch64.  It should be possible to get Desktop to build with your OS's Qt libraries but it may require some changes to the build scripts.

You'd also need to build our dependencies, these should be relatively straightforward using the build scripts in each repo:
- https://github.com/pia-foss/desktop-openvpn
- https://github.com/pia-foss/desktop-wireguard
- https://github.com/pia-foss/desktop-hnsd
- https://github.com/pia-foss/desktop-shadowsocks

Then copy those artifacts to the desktop repo and build the desktop client itself (see README.md).  If you don't intend to use all of the dependency features, you may be able to skip some of them, you'd probably need to remove them from the desktop Qbs projects in that case.

**Comment by kevinlekiller** [comment]
Thanks for the reply, I was trying to build it yesterday, it would get through `--configure` fine, but would fail on `--package` with this error: `Profile "piaqt512" has a non-existent base profile "clang".`,

Will have a go again tonight or tomorrow and see if I can get further.

**Comment by JonathonH-PIA** [comment]
It's been a while on this one, but we finally have arm64 and armhf builds for our latest beta! https://github.com/pia-foss/desktop/releases/tag/2.6.2-beta.1

Give this a try and let us know how it works for you!  I'm also interested in build feedback if you'd like to try building it.  We use Debian Stretch environments for cross builds, if you have `schroot` and `debootstrap` you can set these up with `scripts/chroot/setup.sh`.  You can also install the cross build dependencies in your host OS, but we haven't tested this on Arch.

I'll close this issue since this is now in beta, but please send us feedback or open issues if you find bugs!
