### ISSUE TITLE
PIA sending non-compliant DNS request?

### ISSUE THREAD

**Issue by fumoboy007** [pia-foss/desktop#9]
**Describe the bug**
My intrusion detection system sent me an alert:
> Threat Management Alert 1: Potential Corporate Privacy Violation. Signature ET DNS Non-DNS or Non-Compliant DNS traffic on DNS port Opcode 8 through 15 set. From: 192.168.1.10:53391, to: 199.116.118.176:53, protocol: UDP

The alert is saying a DNS request to 199.116.118.176 (a [Total Server Solutions server](https://ipinfo.io/AS46562/199.116.118.0/24)) is using an unassigned [DNS OpCode](https://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-5).

**To Reproduce**
Not sure yet… but if I remember correctly, the VPN was on.

**Expected behavior**
Any DNS requests should be standards-compliant.

**Observed on:**
 - macOS 10.15.5
 - Version 1.2 (build 04977)

**Comment by JonathonH-PIA** [comment]
@fumoboy007 It sounds like PIA was connected using the OpenVPN protocol over UDP 53.  We provide OpenVPN connectivity over several ports normally used for other services since they are able to penetrate some firewalls.

This is not DNS traffic at all, which is why the traffic was flagged.  We don't offer DNS from the VPN servers' public IPs on any port.

You can choose the protocol and port from Settings > Connection; you may want to use a setting other than UDP 53 if you don't want the traffic to be misinterpreted as DNS.

I'm going to close this since it does not appear to be a bug, but let us know if there's any more to discuss.
